# prometheus.yml

scrape_configs:
  - job_name: web
    static_configs:
      - targets: ["localhost:80"]

  - job_name: db
    static_configs:
      - targets: ["localhost:5432"]

  - job_name: grafana
    static_configs:
      - targets: ["localhost:3000"]

  - job_name: pgadmin
    static_configs:
      - targets: ["localhost:54321"]